<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>add_to_cart_button</name>
   <tag></tag>
   <elementGuidId>d007406c-3e61-4bad-a785-825c5bf6f150</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn_inventory</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@data-test='add-to-cart-${uniqueId}']&#xd;
</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
