<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>item_price</name>
   <tag></tag>
   <elementGuidId>41e24c4f-0baf-4f1e-9e48-808436f5359e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>div[class=&quot;inventory_item_price&quot;]&#xd;
</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.inventory_item_price&#xd;
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
