<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>item_title_links</name>
   <tag></tag>
   <elementGuidId>fbe58df0-addb-45e6-87f8-fc80d44e5f02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[id^=&quot;item_&quot;][id$=&quot;_title_link&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@class='inventory_item_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
