<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>item_description</name>
   <tag></tag>
   <elementGuidId>690f482c-d7cb-4aa0-b2d4-9ac773da1988</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>div[class=&quot;inventory_item_desc&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.inventory_item_desc</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
