<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>product_filter</name>
   <tag></tag>
   <elementGuidId>673614c4-d867-480c-902c-ac4bbbadb737</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[class=&quot;product_sort_container&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
